version: '3'
services:
  samba-timemachine:
    image: irvingpop/samba-timemachine:latest
    network_mode: host
    build: .
    restart: always
    environment:
      TM_USER: juniper
      TM_PW: juniper
      VOLUME_SIZE_LIMIT: 1024000
    volumes:
      - '/atlas/shares:/shares'
      - '/atlas/shares_var:/var'
      - '/etc/localtime:/etc/localtime:ro'
